### ISSUE TITLE
[mac-chrome-1920-board] 이미지 파일 경로 오류

### ISSUE THREAD

**Issue by dongmin132** [100-hours-a-week/5-erica-rho-kcs-community#1]
**버그 설명**
모든 페이지 이미지가  안보입니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인을 하고
2. 게시물 목록에 들어가면 이미지가 뜨지 않습니다

**예상한 동작**
이미지가 잘 나와야됨.

**스크린샷**
![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/114303854/ebbd869a-eeae-42be-9384-b51a0e078007)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: mac
 - Browser chrome
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 이미지 안보이는 이슈

### [ 발생 원인 ]
- 이미지 url이 해당 서버 url로 되어있지 않아서 이미지가 안보임

### [ 해결 방법 ]
- 이미지 url  서버 url에 맞게 보이도록 수정했습니답!

<hr/>

- qa 감사합니답:)
