### ISSUE TITLE
[mac-chrome-1920-post] 댓글 프로필 이미지 안보임

### ISSUE THREAD

**Issue by DohunHyun** [100-hours-a-week/5-erica-rho-kcs-community#10]
**버그 설명**
게시글 상세 페이지에서 댓글에 있는 프로필 사진이 안보입니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 포스트 페이지 진입

**예상한 동작**
이미지가 잘 보여야한다.

**스크린샷**
![스크린샷 2024-04-25 오후 3 23 50](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/33439924/3c2b2488-201b-48e8-8ccd-ba1b9499170c)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: mac
 - Browser : chrome
 - Version [예) 22]

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 이미지 안보이는 이슈

### [ 발생 원인 ]
- 이미지 url이 해당 서버 url로 되어있지 않아서 이미지가 안보임

### [ 해결 방법 ]
- 이미지 url 수정했습니다

<hr/>

- qa 감사합니답 !!!
