### ISSUE TITLE
[mac-chrome-1920-게시물작성] 새로운 게시물 작성이 안됨

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-erica-rho-kcs-community#11]
**버그 설명**
새로운 게시물 작성이 안됨

**재현하는 방법**
동작을 재현하는 단계:
1. Go to '게시물 작성 페이지'
2. 게시물 제목과 내용 작성하고 파일올린 후 등록버튼 클릭

**예상한 동작**
게시물 목록창으로 이동하고, 이동하면 새로 작성된 게시물이 보여야함

**스크린샷**
 
<img width="1470" alt="스크린샷 2024-04-25 오후 3 32 39" src="https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/163278410/afecedaa-6cb5-4398-81de-fe1c5250c366">

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [iOS]
 - Browser [chrome]
 

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 새로운 게시물 작성 안됨

### [ 발생 원인 ]
- 아마도 이미지 파일이 커서 413 에러가 발생하여 작성이 안되는 것으로 생각이 됩니다! 
- 혹은 서버가 터지는 시점에 작성버튼을 클릭했을 가능성이 있습니다 ㅜㅜ

### [ 해결 방법 ]
- 이미지를 최대 50mb 까지 올릴 수 있도록 수정했습니답. 

<hr/>

- 일단 이미지 관련해서는 수정을 했으나, 다른 경우로 새 게시글이 작성이 안되는 것일 수 있어서 다음 qa때 한번 더 봐야 할 것 같습니다 ㅜㅜ
- QA 감사합니다 <3
