### ISSUE TITLE
[맥-크롬-1920px-회원정보 수정 페이지] 닉네임 수정 후 토스트팝업이 사라지지 않습니다.

### ISSUE THREAD

**Issue by bysoyeon** [100-hours-a-week/5-erica-rho-kcs-community#12]
**버그 설명**
회원정보 수정 클릭 후 나타난 '수정완료' 토스트팝업이 사라지지 않습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인
2. 우측 상단 클릭 -> 회원정보 수정 클릭
3. 닉네임 수정 후 '수정하기' 버튼 클릭

**예상한 동작**
닉네임 수정 완료 후 '수정하기' 토스트팝업 일정 시간 노출 후 미노출

**스크린샷**
<img width="1512" alt="image" src="https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/167726398/a796af3a-326f-4de3-a905-d1c7e2ce60c3">

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 닉네임 수정 후 토스트팝업이 사라지지 않습니다

### [ 발생 원인 ]
- 토스트 메세지를 일정 시간 이후에 사라져야 한다는 것을 인지 못했습니다.

### [ 해결 방법 ]
- setTimeout을 통해 2초 뒤에 토스트 메세지가 사라지도록 코드 변경했습니다!

<hr/>

- 코드를 이리저리 고쳐가다 보니 정작 구현해야 할 것을 못했네요 ㅜㅜ QA 감사합니다 👍 👍 👍 👍 👍 👍
