### ISSUE TITLE
[Mac-크롬-1920-헤더] 비로그인 상태에서 헤더 클릭시 접근 가능

### ISSUE THREAD

**Issue by ZZ3n** [100-hours-a-week/5-erica-rho-kcs-community#13]
**버그 설명**
비 로그인 유저가 회원가입 화면에서 헤더 클릭시 
글 리스트 화면으로 접근 가능합니다.
로그인한 상태인 것처럼 보이며, 회원정보 수정에 들어갈 수 있습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 페이지로 이동한다.
2. 헤더의 '아무말 대잔치'를 클릭한다.
3. 글 리스트 페이지로 접근 가능하다.

**예상한 동작**
글 리스트 접근 불가능 하거나, 비 로그인 상태로 보여야 함

**스크린샷**

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: Mac
 - Browser [Chrome]
 - Version [124.0.6367.62(공식 빌드) (arm64)]

**추가적인 내용:**

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 미로그인시에 게시물 목록 접근 가능 이슈

### [ 발생 원인 ]
- 로그인, 회원가입 시에도 navbar에 link가 걸려있어서 작동

### [ 해결 방법 ]
- 해당 url에서는 link 삭제

<hr/>

- 큰일날 뻔 했네요.... 보안 이슈....... 알려주셔서 감사합니다 👍 👍 👍 👍
