### ISSUE TITLE
[Mac-Chrome-1920-게시글 상세 조회] 댓글 수정 버튼 색상 변경

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/5-erica-rho-kcs-community#14]
**버그 설명**
댓글 수정 시에도 버튼 색상이 변경되면 좋을 것 같습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 상세조회 페이지에 접속한다.
2. 댓글 입력 후 등록한다.
3. 수정 버튼을 누르고 댓글 내용을 수정한다.
4. `댓글 수정` 버튼에 마우스를 올린다.

**예상한 동작**
다른 버튼들과 동일하게 버튼 활성화 시 `ACA0EB` -> `7F6AEE` 로 변경

**스크린샷**

https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/78146904/e002873c-8d88-42cc-919b-4a8ac65904db

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 댓글 수정 시 버튼 비활성화

### [ 발생 원인 ]
- input 이벤트를 넣어주지 않아서 발생

### [ 해결 방법 ]
- input event listener 붙여서 해결했습니다


<hr/>

- 댓글 등록에 적용한게 수정 버튼에도 적용되어 있는 줄 알았는데 그러지 않았네요 ㅜㅜ 알려주셔서 감사합니다 :)  QA 감사합니다 🔥
