### ISSUE TITLE
[mac-chrome-1920-로그인] 이메일, 비밀번호 입력 후 로그인 버튼의 색상이 변경되지 않습니다.

### ISSUE THREAD

**Issue by 49EHyeon42** [100-hours-a-week/5-erica-rho-kcs-community#15]
**버그 설명**
로그인 페이지에서 이메일, 비밀번호 입력 후 로그인 버튼의 색상이 ACA0EB에서 7F6AEE로 변경되지 않습니다.

**재현하는 방법**
1. 이메일 입력
2. 비밀번호 입력
3. 버튼 색 확인

**예상한 동작**
로그인 버튼 색 변경

**스크린샷**
비밀번호 입력 전
![스크린샷 2024-04-25 오후 3 22 33](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/78364654/417b90ba-58e8-4eb7-811a-8aec3ca2e8ac)

비밀번호 입력 후
![스크린샷 2024-04-25 오후 3 22 25](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/78364654/6317b158-5d41-4524-aac1-e66f208b6533)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: mac
 - Browser: chrome
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
파이팅

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 이메일, 비밀번호 입력 후 로그인 버튼의 색상이 변경되지 않습니다

### [ 해결 방법 ]
- figma에서 버튼 클릭 시에 유효성 검사를 하고 통과 시에 버튼 색상을 변경해주는 것여서 해당 이슈는 닫겠습니다!

![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/81230764/f7c2cbaa-a0ab-4a97-b57d-bfe1d6d4213c)

<hr/>

- 여러가지 버튼 활성화 경우가 있었네요 ㅜㅜ 다양한 경우 고려해서 적용하겠습니다! QA 감사합니다~~ 👍 👍 🔥
