### ISSUE TITLE
[맥-크롬-1920-비밀번호수정] 프로필 이미지 크기가 다른페이지보다 큰것같습니다.

### ISSUE THREAD

**Issue by carter468** [100-hours-a-week/5-erica-rho-kcs-community#16]
**버그 설명**
비밀번호 수정 페이지 프로필 이미지 크기가 다른 페이지보다 큰것같습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인하고
2. 비밀번호수정으로 이동

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.

**스크린샷**
<img width="1493" alt="스크린샷 2024-04-25 오후 3 28 07" src="https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/105616992/dec5c9f9-ccea-4a8c-b1f4-7b0d20fb977e">
<img width="1501" alt="스크린샷 2024-04-25 오후 3 29 18" src="https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/105616992/c1c7a39c-1e6e-4a18-bf7e-9ff906c29f1d">

**데스크톱(다음 정보를 작성해 주세요):**
 - 맥
 - 크롬

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 프로필 이미지 크기가 다른페이지보다 큰것같습니다

### [ 발생 원인 ]
- css에 사진 크기를 지정했으나 적용되지 않음

### [ 해결 방법 ]
- html 태그 내에서도 강제로 이미지 크기 36px 36px로 지정했습니다
![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/81230764/e8d6cfe7-a33c-4310-b9b9-ce40cf2747f6)

<hr/>

- 저런 이슈가 있는 줄 몰랐습니다 ㅜㅜ QA 개인적으로 다시 또 진행해서 보완하겠습니답 감사합니다 🤗🤗🤗🤗🤗
