### ISSUE TITLE
[맥-크롬-1920-회원정보수정페이지] 닉네임 수정 변경 오류

### ISSUE THREAD

**Issue by grulla99** [100-hours-a-week/5-erica-rho-kcs-community#18]
**버그 설명**
닉네임 변경시 변경이 되지 않음

**재현하는 방법**
동작을 재현하는 단계:
1. 닉네임 변경 전 10글자 이상 작성 후 수정하기
2. 10글자 이하로 변경 후 수정 버튼 누르기

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.!

[스크린샷 2024-04-25 오후 3 24 41](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/122856840/bd64e582-2ec5-4ad8-a94e-68b523476bb0)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: 맥
 - Browser 크롬

**추가적인 내용:**

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 닉네임 수정 변경 오류

### [ 발생 원인 ]
- 닉네임만 수정 시 이미지 url이 다른 url로 변경 저장이 되어서 (오타로 인해 ㅜㅜ) 이미지가 안보였던 것 같습니다.
- 닉네임 최대 10글자 제한을 안걸어놨습니다..

### [ 해결 방법 ]
- 닉네임 10글자 제한
- 이미지 url 변경 저장에서 생겨난 오타 고쳐서 잘 나오게 수정했습니다!

<hr/>

- 진짜 저 혼자 qa 했을 때 안나왔었던 오류라서 몰랐습니다 ㅜㅜ qa 감사합니다!
