### ISSUE TITLE
[mac-chrome-1920-게시글상세페이지] 페이지 로딩 시 빈 댓글창 노출

### ISSUE THREAD

**Issue by ej31** [100-hours-a-week/5-erica-rho-kcs-community#19]
**버그 설명**
페이지 로딩시 스켈레톤 이미지가 있으면 좋을 것 같음
유저에게 빈 댓글창만 보이는 것이 좋은 경험을 아닐것 같음

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 상세 페이지 이동
2. 유저에게 빈 댓글 창만 노출됨

 
**예상한 동작**
게시글 호출 동안 스켈레톤 이미지 혹은 제목은 먼저 보일것으로 예상

**스크린샷**

https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/25720120/2248e591-56da-43f0-bec9-d45a04016f02

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 페이지 로딩 시 빈 댓글창 노출

### [ 발생 원인 ]
- 글 로딩 중에는 노출이 안되어 댓글 작성 창만 보임

### [ 해결 방법 ]
- 스켈레톤 추가

<hr/>

- skeleton 추가 했습니다!
