### ISSUE TITLE
[MAC-Chrome-1920-/board/post] 게시글 작성을 연타하면 같은 글이 여러개 올라갑니다

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/5-erica-rho-kcs-community#2]
**버그 설명**
게시글 작성 버튼을 빠르게 연타하면 글이 여러개 올라갑니다

**재현하는 방법**
동작을 재현하는 단계:
1. Go to /board/post
2. write all content
3. click "완료" 빠르게
4. 여러 글 작성됨

**예상한 동작**
글이 하나만 올라가기

**스크린샷**
<img width="700" alt="스크린샷 2024-04-25 오전 1 14 10" src="https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/98401161/6eb714bf-b30c-4d58-ad6f-47fea1826986">

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 게시글 작성을 연타하면 같은 글이 여러개 올라갑니다

### [ 발생 원인 ]
- 버튼 click 이벤트 리스너는 클릭 할 때마다 이벤트가 발생 -> 버튼 누른 수 만큼 post 생성

### [ 해결 방법 ]
- 버튼 click 시 바로 ```button.unabled = true``` 를 설정하여 이벤트 중복 방지

<hr/>

- 소중한 QA 감사합니다...............
