### ISSUE TITLE
[mac-chrome-1920-메인 포스트] 404에러

### ISSUE THREAD

**Issue by moolmin** [100-hours-a-week/5-erica-rho-kcs-community#3]
**버그 설명**
사이트 접속이 갑자기 안됩니다

**재현하는 방법**
동작을 재현하는 단계:
1. https://proud-socks-kick.loca.lt/ 접속
2. 404에러

**예상한 동작**
사이트가 접속하기

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: 맥
 - Browser: 크롬
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 404에러, 사이트 접속 불가 

### [ 발생 원인 ]
- local tunnel이 이슈가 있어서 웹 서버가 꺼짐

### [ 해결 방법 ]
- local tunnel 이슈라 해결은 하진 못했지만, 계속 서버를 재실행

<hr/>

- 처음 써보는 툴이라 위의 이슈가 발생할 것이라고 생각 못헀습니다ㅜㅜ 알려주셔서 감사합니다 :)
- 다음에 더 보완해서 QA 신청하겠습니다..! 그때도 잘 부탁드립니다 🤩
