### ISSUE TITLE
[mac-크롬-1920-signUp] 회원가입 이미지 업로드 시 모든 파일 선택 가능

### ISSUE THREAD

**Issue by ej31** [100-hours-a-week/5-erica-rho-kcs-community#4]
**버그 설명**
회원가입 시도 시 이미지 업로드 할 때 모든 파일을 선택 할 수 있음
jpg, png 와 같은 이미지 확장자만 업로드 할 수 있어야함

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 페이지 이동
2. 프로필 이미지 클릭

**예상한 동작**
이미지만 선택 할 수 있어야한다.

**스크린샷**
![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/25720120/b4d94a5c-6836-4093-83d0-9171747ceb78)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: mac
 - Browser chrome
 - Version 124

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 회원가입 이미지 업로드 시 모든 파일 선택 가능

### [ 발생 원인 ]
- `<input id="imageInput" type="file" accept="images/*" />` 코드에서 accept="images" 로 되어있었음

### [ 해결 방법 ]
- `<input id="imageInput" type="file" accept="image/*" />` 로 수정

<hr/>

- 회원가입때만 그런줄 알았는데 프로필 업데이트 할때도 같은 문제가 있었습니다 ㅜㅜ 꼼꼼히 봤어야 했는데.. ㅜㅜ 
- qa 감사합니답
