### ISSUE TITLE
[mac-chrome-1920-loginpage] 회원가입 버튼 너무 작음

### ISSUE THREAD

**Issue by ej31** [100-hours-a-week/5-erica-rho-kcs-community#5]
**버그 설명**
회원가입 버튼 사이즈가 너무 작음

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.

**스크린샷**
![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/25720120/e0007e0a-d412-4cd6-8b35-f5353b83dd1c)

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 회원가입 버튼 너무 작음 

### [ 발생 원인 ]
- 버튼 내 글씨 크기가 10px 로 설정되어 있어 작은 크기로 노출

### [ 해결 방법 ]
- `font-size: 1.3rem;` 로 수정하여 글씨 크기 13px 적용

   ![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/81230764/b52cf4d4-81b0-4966-a0d4-5844e21d6857)

<hr/>

- style에도 신경쓰겠습니답... QA 감사합니다 🔥
