### ISSUE TITLE
[mac-chrome-1920-회원가입] 회원가입진행 불가 (419 status)

### ISSUE THREAD

**Issue by ej31** [100-hours-a-week/5-erica-rho-kcs-community#6]
**버그 설명**
```json

{
"email":"안녕@하세요.반갑습니다",
"password":"12qwQW!@",
"nickname":"12qwQW!@",
"profile_image":"data:image/png;base64,iVBORw..."
}
```

위와 같은 payload 를 서버에 보내서 회원가입 시도했으나 419 에러 발생

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 페이지 이동
2. 가입 정보는 상단확인
3. 419 에러 발생

**예상한 동작**
정상적인 회원가입

**스크린샷**
![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/25720120/ad59806e-2536-4880-8ef5-49a960fcde59)

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 회원가입진행 불가 

### [ 발생 원인 ]
- 아마도 이미지 파일이 커서 413 에러가 발생하여 가입이 안되는 것으로 생각이 됩니다! 

### [ 해결 방법 ]
- 이미지를 최대 50mb 까지 올릴 수 있도록 수정했습니답. 

<hr/>

- 일단 이미지 관련해서는 수정을 했으나, 다른 경우로 회원가입이 안되는 것일 수도 있어서 좀 더 봐보겠습니답 ㅜㅜ
