### ISSUE TITLE
[맥-크롬-1920-메인페이지, 회원정보수정페이지] 이미지파일을 불러오지 못합니다.

### ISSUE THREAD

**Issue by sen2y** [100-hours-a-week/5-erica-rho-kcs-community#7]
**버그 설명**
유저프로필 이미지파일이 깨져요.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인후 메인페이지 헤더에도 이미지가 뜨지않고
2. 댓글작성해도 이미지 깨지고
3. 회원정보수정탭에서도 이미지 깨져요

**예상한 동작**
회원프로필 이미지가 뜬다

**스크린샷**
![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/83276834/a74a5513-b89f-4497-8aba-23293a7b16cc)
![image](https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/83276834/f195897d-6208-4bae-b6d6-013b58b1895c)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) 맥

**Comment by erica0321** [comment]
### [ 발생 이슈]
- 이미지 안보이는 이슈

### [ 발생 원인 ]
- 이미지 url이 해당 서버 url로 되어있지 않아서 이미지가 안보임

### [ 해결 방법 ]
- 이미지 url  서버 url에 맞게 보이도록 수정했습니답!

<hr/>

- qa 감사합니답:)
