### ISSUE TITLE
[OS-브라우저-가로사이즈-페이지명] 안건

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-erica-rho-kcs-community#8]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
게시물 작성이 안됩니다.

**재현하는 방법**
동작을 재현하는 단계:
1. Go to '게시물 작성'
2. 제목, 내용 입력 후 게시물 작성 클릭
3. 안됨

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.
게시물 목록 리스트로 돌아와야 하고, 내가 쓴 게시물이 보여야 한다.

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="1470" alt="스크린샷 2024-04-25 오후 3 23 52" src="https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/163278410/84894ad0-c665-44ec-bbd2-daf388b83a7f">

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [iOS]
 - Browser [chrome]

**Comment by erica0321** [comment]
이전 이슈와 같은 이슈인 것 같아 넘어가겠습니다!
