### ISSUE TITLE
[맥-크롬-1920-회원가입 페이지] 회원가입 버튼 활성화가 되지 않습니다.

### ISSUE THREAD

**Issue by lucy726j** [100-hours-a-week/5-erica-rho-kcs-community#9]
**버그 설명**
 회원가입 버튼이 활성화 되지 않습니다

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 페이지를 들어간다.
2. 프로필 사진, 이메일, 비밀번호, 비밀번호 확인, 닉네임 모두 유효성 검사에 맞게 입력 한다.
3. 버튼이 활성화 되지 않는다.

**예상한 동작**
버튼이 활성화 되고 로그인 페이지로 넘어간다. 

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="782" alt="스크린샷 2024-04-25 오후 3 22 56" src="https://github.com/100-hours-a-week/5-erica-rho-kcs-community/assets/167487987/6712c0e6-bac0-4253-9e35-154025aa590e">

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: 맥 
 - Browser : chrome
 - Version: 버전 123.0.6312.87

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by erica0321** [comment]
### [ 발생 이슈]
회원가입 버튼 활성화가 되지 않습니다

### [ 발생 원인 ]
- 회원가입 버튼 클릭 시 버튼 색상 변경 코드를 작성하지 않음

### [ 해결 방법 ]
- 회원가입 버튼 클릭하여 회원가입 성공 시 버튼 색상 변경하는 것으로 바꾸었습니다. (만약 버튼 클릭시 변경이 아니였다면 comment 달아주세요!)

<hr/>

- QA 감사합니다~~ 많이 보완해서 다음에 QA 신청할게욥 그때도 잘 부탁드립니답 👍 👍 👍  🔥
